# Problem Statement:
A leading retail company wants to better understand its customers' shopping behavior in order to improve sales, customer satisfaction, and long-term loyalty. The management team has noticed changes in purchasing patterns across demographics, product categories, and sales channels (online vs. offline). They are particularly interested in uncovering which factors, such as discounts, reviews, seasons, or payment preferences, drive consumer decisions and repeat purchases.
You are tasked with analyzing the company's consumer behavior dataset to answer the following overarching business question:
**"How can the company leverage consumer shopping data to identify trends, improve customer engagement, and optimize marketing and product strategies?"**

**Deliverables :**
1. Data Preparation & Modeling (Python): Clean and transform the raw dataset for analysis.
2. Data Analysis (SQL): Organize the data into a structured format, simulate business transactions, and run queries to extract insights on customer segments, loyalty, and purchase drivers.
3. Visualization & Insights (Power BI): Build an interactive dashboard that highlights key patterns and trends, enabling stakeholders to make data-driven decisions.
4. Report and Presentation: Write a clear project report summarizing your key findings and business recommendations. Prepare a presentation that visually communicates insights and actionable recommendations to stakeholders.
5. GitHub Repository: Include all Python scripts, SQL queries, and dashboard files in a well-structured repository.

# Importing Necessary Libraries & Dataset
Here, I have imported all the necessary libraries to see the dataset and begin the analysis.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/kaggle/input/datasets/kingshukdatta18/customer-shopping-behaviour-dataset/customer_shopping_behavior.csv")

In [3]:
# dataset of 10 rows
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

## Dataset Analysis
I have used ".info()" to further analyze the dataset.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

I  have used **".describe()"** to check the summary statistics. By default, **".describe()"** gives the summary statistics of the numerical columns only.

But there is a way to include **"catagorical"** columns also. In the first bracket - () -> we have to write **include= "all"**.

In [5]:
df.describe(include= "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

Now I am checking the missing / null values. This is a very important step as it can affect the analysis.

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

By checking, I have found that **'Review Rating'** has a total of **37** null values. To go to further analysis, I have to do something about the null values.

## Approach to Mitigate the null values.
I can do mean or median for the null values. But there is a problem. For Mean, it can easily be effected by the outliers. For Median, it is robust to outliers. I can replace the null values with overall "Median" of the entire column. In logic, It will be okay but there is a catch. All the null values will be replaced by a generalized median, which can introduce bias to the dataset. But in dataset, we have different types of catagories. So, rather than replacing with general median, I can Replace it by catagory wise median. That way I can get the genuine results.

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
# checking after the action
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

# Transforming Dataset for Data Analysis
In the dataset, all the column names has spaces and mixture of upper case  and  lower case characters. This will create a problem during the coding session. So, to fix this I have transformed the column names into snake case.

For Example: We have a column called "Customer ID" insted of writing this we can write "customer_id" to reduce the human error and easier typing.

In [9]:
# checking all the column names
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

To change all the column names to the "Snake Case" I first transform all the column names into lower case and the replaced all the whiitespace to '_'.

**Note: Lastly I have replaced 'purchase_amount_(usd)' to 'purchase_amount'**

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns= {'purchase_amount_(usd)' : 'purchase_amount'})

In [11]:
# after changing
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

## Feature Engineering
I have created new columns using feature Engineering called "age_group" which will consist of customers in groups of "Young Adult","Adult","Middle-aged" and "Senior".

".qcut()" method is used for the grouping.

* **Why this new column?** -> To understand easily about the customer age group and for marketing stragies it is helpfull.

In [12]:
# create a column 'age_group'
labels = ["Young Adult","Adult","Middle-aged", "Senior"]
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [13]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

I have created another column called "purchase_frequency_days".
* **Why create this column?** -> because we have "frequency_of_purchases" which tells about the purchase, but in text form. That is why this new column.

In [14]:
frequency_mapping = {
    "Fortnightly" : 14,
    "Weekly" : 7,
    "Monthly" : 30,
    "Quarterly" : 90,
    "Bi-Weekly" : 14,
    "Annually" : 365,
    "Every 3 Months" : 90
}

# creating column and the records under the column.
df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [15]:
df[["purchase_frequency_days", "frequency_of_purchases"]].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [16]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

I am deciding if both of the columns are similar or different. Because sometimes shops gives discounts without promocodes.

In [17]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

I have checked if all the values of the both columns are similar. If similar, then we can drop a column and the result is "True". So, T have removed "promo_code_used".

In [18]:
df = df.drop('promo_code_used', axis= 1)

In [19]:
# checking  if the change is applied
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

# Connect The Notebook to the SQL
I have connected this notebook to  the sql. For that, I have installed "psycopg2-binary" and "sqlalchemy"

In [20]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 56.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install psycopg2

Requirement already satisfied: psycopg2 in /usr/local/lib/python3.12/dist-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

## For PostGre SQL
1. Connect to PostgreSQL.
2. Replace placeholders with the actual details.
3. Load Dataframe into PostGreSQL.

In [22]:
from sqlalchemy import create_engine

username = 'postgres' 
password = '12345' 
host = 'bore.pub' 
port = '62035'
database = 'customer_behavior' 

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "customer"

try:
    print("Starting data upload through the tunnel... this might take a minute.")
    
    # chunksize=500 sends the data in batches of 500 rows to prevent tunnel timeouts
    df.to_sql(table_name, engine, if_exists="replace", index=False, chunksize=500)
    
    print(f"Data successfully loaded into table '{table_name}'!")

except Exception as e:
    print(f"An error occurred: {e}")

finally:
    # This ensures the connection is closed cleanly, preventing PendingRollbackErrors in the future
    engine.dispose()

Starting data upload through the tunnel... this might take a minute.
An error occurred: (psycopg2.OperationalError) connection to server at "bore.pub" (161.35.110.36), port 62035 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "bore.pub" (2604:a880:400:d1:0:3:c75b:a001), port 62035 failed: Network is unreachable
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

### Pushing Data to My Local Database

I ran into a problem trying to connect this Kaggle notebook directly to my local PostgreSQL database. Because Kaggle runs on a cloud server, using `localhost` in the connection string just threw a "Connection refused" error. Kaggle couldn't see my laptop's private network.

To get around this, I used a free tunneling tool called **Bore**. It creates a secure, temporary bridge between my local computer and the internet.

**Here is how I set it up:**

1. I ran this command in my computer's terminal to expose my local Postgres port (5432):
```bash
bore local 5432 --to bore.pub

```


2. Bore gave me a public address (`bore.pub`) and a random 5-digit port number.
3. I updated the Python connection string to use that new host and port instead of `localhost`.

**Fixing the Timeout Issue**
Once the connection was working, I hit a `PendingRollbackError` when trying to upload the dataframe. This happened because the public tunnel is slower than a normal local network. Trying to shove the entire dataset through at once caused the connection to choke and time out.

The fix was simple: I added `chunksize=500` to the `to_sql()` function. This tells pandas to send the data over in small batches of 500 rows, which kept the tunnel stable and successfully loaded everything into my database.

**The Final Code:**

```python
from sqlalchemy import create_engine

# Using the temporary credentials from the Bore tunnel
username = 'postgres' 
password = '12345' 
host = 'bore.pub' 
port = '19728' # The port Bore assigned me
database = 'customer_behavior' 

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "customer"

try:
    # chunksize=500 is required to prevent the tunnel from timing out
    df.to_sql(table_name, engine, if_exists="replace", index=False, chunksize=500)
    print("Data successfully loaded!")
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    engine.dispose() # Close the connection cleanly

```